import AppSidebar from "@/components/AppSideBar";
import { DashboardLayout } from "@/components/DashboardLayout";
import HandleWebhookTrigger from "@/components/HandleWebhookTrigger";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import "./github-markdown-light.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`} suppressHydrationWarning>
        <SidebarProvider>
          <AppSidebar />
          <DashboardLayout>{children}</DashboardLayout>
        </SidebarProvider>
        <Toaster />
        <HandleWebhookTrigger />
      </body>
    </html>
  );
}
